# read .env file
spring.config.import=optional:file:.env[.properties]

# datasource from environment variables
spring.datasource.url=jdbc:sqlite:database.db
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# SQLite config
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.jpa.properties.hibernate.dialect=org.hibernate.community.dialect.SQLiteDialect


# Flyway
spring.flyway.enabled=true

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
